name: circular_progress_pie
description: "A highly customizable pie chart progress indicator for Flutter with smooth animations, gradients, and multiple animation types."
version: 0.0.2
homepage: https://github.com/abqamar/circular_progress_pie.git
repository: https://github.com/abqamar/circular_progress_pie.git

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0